name: generate 3d contribution graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: aly-abbas11

      - name: Commit and push
        run: |
          git config user.name aly-abbas11
          git config user.email forworkuse10@gmail.com
          git add -A
          git commit -m "Update 3D contribution graph" || exit 0
          git push
